Implementação do Banco de Dados
Gustavo-Dorigon-Coan/monorepo-trello pull request #3
Opened 2021-08-12 01:44 UTC by Pietrogon

Implementa arquivo Dockerfile com a configuração da imagem docker, adiciona arquivo com os comandos para rodar o banco de dados.

Comandos para subir o banco:

`cd Database`
`docker build .`
`sh DBInit.sh`

2021-08-12 01:49 UTC, wesleyfuchter commented
Sugiro adicionar um arquivo do docker-compose para facilitar o deployment do banco de dados. Será útil também para fazer deployment dos outros serviços depois.

2021-08-12 01:50 UTC, wesleyfuchter requested changes
Bom trabalho, apenas uma sugestão.

2021-08-12 01:50 UTC, wesleyfuchter commented on Database/DBInit.sh
> +docker build -t trellodb .
Docker-compose me parece uma estratégia mais interessante para rodar o banco de dados.

2021-08-12 01:55 UTC, Gustavo-Dorigon-Coan approved these changes
Show de bola!!

2021-08-12 14:06 UTC, Pietrogon commented
![](https://github.trello.services/images/mini-trello-icon.png) [TL015 - Criar Banco de dados MYSQL.](https://trello.com/c/J7FLk96D/15-tl015-criar-banco-de-dados-mysql)

2021-10-18 22:56 UTC, Pietrogon commented
Resolvido docker compose em outro PR.

2021-10-18 22:56 UTC, closed without merging